name: Luacheck

on:
  push:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - '.github/workflows/luacheck.yml'
  pull_request:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - '.github/workflows/luacheck.yml'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: lua
